// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/Project/Agent Panel/frontend/src/pages/ai/models/index';
import model_2 from 'D:/Project/Agent Panel/frontend/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'ai.index', model: model_1 },
model_2: { namespace: '@@initialState', model: model_2 },
} as const
