// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from 'D:/Project/Agent Panel/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import SettingOutlined from 'D:/Project/Agent Panel/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import AppstoreOutlined from 'D:/Project/Agent Panel/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import FolderOutlined from 'D:/Project/Agent Panel/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/FolderOutlined';
import RobotOutlined from 'D:/Project/Agent Panel/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/RobotOutlined';
export default { DashboardOutlined, SettingOutlined, AppstoreOutlined, FolderOutlined, RobotOutlined };
