apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-panel.fullname" . }}-secret
  namespace: {{ include "agent-panel.namespace" . }}
  labels:
    {{- include "agent-panel.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  APP_SECRET_KEY: {{ .Values.secrets.appSecretKey | quote }}
  STORAGE_ACCESS_KEY: {{ .Values.storage.accessKey | quote }}
  STORAGE_SECRET_KEY: {{ .Values.storage.secretKey | quote }}
