// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'D:/Project/Agent Panel/frontend/src/.umi-production/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from 'D:/Project/Agent Panel/frontend/src/.umi-production/plugin-locale';
export { Provider, useModel } from 'D:/Project/Agent Panel/frontend/src/.umi-production/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/Project/Agent Panel/frontend/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from 'D:/Project/Agent Panel/frontend/src/.umi-production/plugin-access/types.d';
export * from 'D:/Project/Agent Panel/frontend/src/.umi-production/plugin-antd/types.d';
export * from 'D:/Project/Agent Panel/frontend/src/.umi-production/plugin-layout/types.d';
export * from 'D:/Project/Agent Panel/frontend/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/Project/Agent Panel/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.6_f6ef47ccb6c1da1a053b72892ec06e00/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'D:/Project/Agent Panel/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.6_f6ef47ccb6c1da1a053b72892ec06e00/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/Project/Agent Panel/frontend/node_modules/.pnpm/umi@4.6.65_@babel+core@7.29_75582dbde02798d579d2d4531855c295/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
