// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from 'D:/Project/Agent Panel/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.6_f6ef47ccb6c1da1a053b72892ec06e00/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
